apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-vault-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: app-vault-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: apps/dev/myapp # change to your Vault secret path
        property: DATABASE_URL
