apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-params
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameterstore
    kind: ClusterSecretStore
  target:
    name: app-params
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: /apps/dev/myapp/DATABASE_URL # change to your SSM parameter path
