apiVersion: apps/v1
kind: Deployment
metadata:
  name: ondemand-workload-example
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ondemand-workload-example
  template:
    metadata:
      labels:
        app: ondemand-workload-example
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: eks.amazonaws.com/capacityType
                    operator: In
                    values:
                      - ON_DEMAND
      containers:
        - name: app
          image: public.ecr.aws/docker/library/nginx:stable
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
