serviceAccount:
  server:
    create: true
    name: velero-server

credentials:
  useSecret: false

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.10.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: terraform-eks-velero-backups # change to your backup bucket
      default: true
      config:
        region: us-east-1 # change to your region
  volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: us-east-1 # change to your region

schedules:
  daily:
    schedule: "0 3 * * *"
    template:
      ttl: 168h
      includedNamespaces:
        - "*"
